### ISSUE TITLE
mongodb+srv urls with querystring parameters cause the forum to fail

### ISSUE THREAD

**Issue by regisb** [overhangio/tutor-forum#16]
mongodb+srv urls are introduced in this PR: https://github.com/overhangio/tutor-forum/pull/10
But querystring parameters will not work in the forum because of the way the `MONGOHQ_URL`variable is generated:

    MONGOHQ_URL="$MONGODB_HOST/$MONGODB_DATABASE"

We need to modify the definition of `MONGOHQ_URL` such that querystring parameters are supported. If possible, we should take this opportunity to get rid of the forum entrypoint entirely.

**Comment by regisb** [comment]
@ghassanmas can you please describe how you launched a Mongodb cluster and how you defined the mongodb host url that caused the error you observed?

**Comment by ghassanmas** [comment]
1- Generating a cluster through atlass 
2- setting the following configuration in tutor `config.yml`
```yml
MONGODB_AUTH_MECHANISM: SCRAM-SHA-1
MONGODB_HOST: mongodb+srv://username:password@x-host.mongodb.net/?retryWrites=true&w=majority
MONGODB_USE_SSL: true
RUN_MONGODB: false
```
- The above setting worked from lms/cms but not aginst the PR #10 (for the forum for the reason mentioned above).
- I haven't tried to do that without PR #10 i.e. default version/olive
